apiVersion: v1
kind: Pod
metadata:
  name: apache2pod1
spec:
  containers:
    - name: apache2
      image: "ubuntu/apache2:2.4-22.04_beta"
      ports:
        - containerPort: 80
          name: http 
          protocol: TCP